### ISSUE TITLE
Minimum Viable Product: Roadmap 🍍

### ISSUE THREAD

**Issue by mertbozkir** [PanoEvJ/Tiny_Agents#30]
- [ ] Plug into application (@jcolano working on creating agents from JSON)
- [ ] Chainlit application UI
- [ ] Shanaka will recreate the use-case!
